spring.sql.init.encoding=utf-8
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.ddl-auto=create-drop
#spring.jpa.defer-datasource-initialization=true

roomescape.auth.jwt.secret=TbS+vo0mJ3SHXcryNYVaUmy0LHRDJU21ca5x02Ga4K6X2BPFFrkox+hYb2IC6n8yf47cR+expaFMmlAo4fB6Iw==
roomescape.auth.jwt.expiry=3600000
