spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

roomescape:
  auth:
    jwt:
      secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="