spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      encoding: utf-8

jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789AB